# Generated by Django 5.0.1 on 2024-02-23 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('python', 'Python'), ('java', 'Java')], default='python', max_length=25)),
                ('duration', models.IntegerField(verbose_name='Duration In Months')),
                ('fees', models.IntegerField(verbose_name='Fees In RS.')),
            ],
        ),
        migrations.CreateModel(
            name='BatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=25)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batch.coursedetails')),
            ],
        ),
    ]
